<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-Site-DC9AFDF5-34D2-4810-A8EA-C2AF875AFF67</UserSecretsId>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <AssemblyName>Site</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\js\assets\vendor\**" />
    <Content Remove="wwwroot\js\assets\vendor\**" />
    <EmbeddedResource Remove="wwwroot\js\assets\vendor\**" />
    <None Remove="wwwroot\js\assets\vendor\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\00000000000000_CreateIdentitySchema.cs" />
    <Compile Remove="Data\Migrations\00000000000000_CreateIdentitySchema.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822121151_Site_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200822121151_Site_InitialCreate.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822181538_Site_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200822181538_Site_InitialCreate.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822181939_Temp.cs" />
    <Compile Remove="Data\Migrations\20200822181939_Temp.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822232858_Site_StorePhoneNumber.cs" />
    <Compile Remove="Data\Migrations\20200822232858_Site_StorePhoneNumber.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822233148_Site_StorePhoneNumber.cs" />
    <Compile Remove="Data\Migrations\20200822233148_Site_StorePhoneNumber.Designer.cs" />
    <Compile Remove="Data\Migrations\20200822233649_Site_StorePhoneNumber.cs" />
    <Compile Remove="Data\Migrations\20200822233649_Site_StorePhoneNumber.Designer.cs" />
    <Compile Remove="Data\Migrations\20200829042554_Site_Referrals_UserPics.cs" />
    <Compile Remove="Data\Migrations\20200829042554_Site_Referrals_UserPics.Designer.cs" />
    <Compile Remove="Data\Migrations\20200901022135_Products_Schema.cs" />
    <Compile Remove="Data\Migrations\20200901022135_Products_Schema.Designer.cs" />
    <Compile Remove="Data\Migrations\20200905033443_Schema_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200905033443_Schema_InitialCreate.Designer.cs" />
    <Compile Remove="Data\Migrations\20200905045525_Schema_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200905045525_Schema_InitialCreate.Designer.cs" />
    <Compile Remove="Data\Migrations\20200905140358_Schema_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200905140358_Schema_InitialCreate.Designer.cs" />
    <Compile Remove="Data\Migrations\20200905144432_Schema_InitialCreate.cs" />
    <Compile Remove="Data\Migrations\20200905144432_Schema_InitialCreate.Designer.cs" />
    <Compile Remove="Migrations\20200909225337_ProductReviews_Schema.cs" />
    <Compile Remove="Migrations\20200909225337_ProductReviews_Schema.Designer.cs" />
    <Compile Remove="Migrations\20200909232528_ProductReviews_Schema.cs" />
    <Compile Remove="Migrations\20200909232528_ProductReviews_Schema.Designer.cs" />
    <Compile Remove="Migrations\20200909233042_ProductReviews_Schema.cs" />
    <Compile Remove="Migrations\20200909233042_ProductReviews_Schema.Designer.cs" />
    <Compile Remove="Migrations\20200915051301_ProductTags_Schema.cs" />
    <Compile Remove="Migrations\20200915051301_ProductTags_Schema.Designer.cs" />
    <Compile Remove="Migrations\20200915052007_ProductTags_Schema.cs" />
    <Compile Remove="Migrations\20200915052007_ProductTags_Schema.Designer.cs" />
    <Compile Remove="Migrations\20201008050521_SitePayment_Schema.cs" />
    <Compile Remove="Migrations\20201008050521_SitePayment_Schema.Designer.cs" />
    <Compile Remove="Migrations\20201009065601_SitePayment_ExternalRef.cs" />
    <Compile Remove="Migrations\20201009065601_SitePayment_ExternalRef.Designer.cs" />
    <Compile Remove="Migrations\20201010001302_SiteUserAndReferrerUser.cs" />
    <Compile Remove="Migrations\20201010001302_SiteUserAndReferrerUser.Designer.cs" />
    <Compile Remove="Migrations\20201010020343_SiteUserAndReferrerUser.cs" />
    <Compile Remove="Migrations\20201010020343_SiteUserAndReferrerUser.Designer.cs" />
    <Compile Remove="Migrations\20201010021354_SiteUserAndReferrerUser.cs" />
    <Compile Remove="Migrations\20201010021354_SiteUserAndReferrerUser.Designer.cs" />
    <Compile Remove="Migrations\20201010022332_UserAccounts_AccountEntry.cs" />
    <Compile Remove="Migrations\20201010022332_UserAccounts_AccountEntry.Designer.cs" />
    <Compile Remove="Migrations\20201021032929_Payment_Charge_Column.cs" />
    <Compile Remove="Migrations\20201021032929_Payment_Charge_Column.Designer.cs" />
    <Compile Remove="Migrations\20201028164041_ExtraColumns_Withdraw_Charge.cs" />
    <Compile Remove="Migrations\20201028164041_ExtraColumns_Withdraw_Charge.Designer.cs" />
    <Compile Remove="Migrations\20201220042335_FlashDeals_Schemas.cs" />
    <Compile Remove="Migrations\20201220042335_FlashDeals_Schemas.Designer.cs" />
    <Compile Remove="Migrations\20201220051113_FlashDeals_Schemas_Decimals.cs" />
    <Compile Remove="Migrations\20201220051113_FlashDeals_Schemas_Decimals.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.35" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.7" />-->
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />

    <!--<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.4" />-->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Migrations\" />
    <Folder Include="wwwroot\assets\images\" />
    <Folder Include="wwwroot\fonts\" />
    <Folder Include="wwwroot\images\adr_images\" />
    <Folder Include="wwwroot\images\uploads_docs\" />
    <Folder Include="wwwroot\js\assets\" />
    <Folder Include="wwwroot\lib\simple-line-icons\dist\css\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\site.js" />
    <None Include="wwwroot\lib\owl-carousel\dist\LICENSE" />
    <None Include="wwwroot\lib\owl-carousel\dist\owl.carousel.js" />
    <None Include="wwwroot\lib\owl-carousel\dist\owl.carousel.min.js" />
    <None Include="wwwroot\lib\owl-carousel\dist\README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sellers\sellers.csproj" />
    <ProjectReference Include="..\shared\Shared.csproj" />
    <ProjectReference Include="..\siteinfo\siteinfo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages\Admin\Stores\Activate - Copy.cshtml.cs">
      <DependentUpon>Activate.cshtml.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
